[package]
name = "lt_dbg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"

nix = "0.26.1"
rustyline = "10.0.0"
